version: '3.7'
services:
  fp-elb:
    build:
      context: fp-elb
      dockerfile: Dockerfile
    image: registry.gitlab.com/aperez4/fp/fp-elb:latest
    # image: traefik:2.2
    # command: --web --api --docker --docker.domain=traefik.test --logLevel=DEBUG
    command: >
      --providers.docker
      --providers.docker.exposedbydefault=true
      --providers.docker.constraints="Label(`constraints.zone`, `fp`)"
      --entryPoints.http.address=:80
      --accesslog
      --log.level=DEBUG
      --api.insecure=true
      --api=true
      --api.dashboard=true
    ports:
      - "9800:80"
      - "9801:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     #  - ./fp-elb/traefik/conf:/toml
     #  - ./fp-elb/traefik/traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "constraints.zone=fp"
    networks:
      private:
        aliases:
          - "fp-elb"
      public:

  fp-orders:
    build:
      context: fp-service-orders
      dockerfile: Dockerfile 
    image: registry.gitlab.com/aperez4/fp/fp-orders:latest
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "fp-orders"
      public:
    ports:    
      - "9803-9805:10011"  
    labels:
      - "constraints.zone=fp"
      - "traefik.http.routers.fp-orders.entrypoints=http"
      - "traefik.http.routers.fp-orders.rule=PathPrefix(`/api/v1/tea`)"
      - "traefik.http.services.fp-orders.loadbalancer.server.port=10011"
      - "traefik.backend=fp-orders"
      - "traefik.port=10011"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.enable=true"
  fp-feedback:
    build:
      context: fp-service-feedback
      dockerfile: Dockerfile
    image: registry.gitlab.com/aperez4/fp/fp-feedback:latest
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "fp-feedback"
      public:
    ports:    
      - "9806-9808:3000"  
    labels:
      # comment out for test only 
      - "constraints.zone=fp"
      - "traefik.http.routers.fp-feedback.rule=PathPrefix(`/feedback`, `/atom`)"
      - "traefik.http.services.fp-feedback.loadbalancer.server.port=3000"
      - "traefik.backend=fp-feedback"
      - "traefik.port=3000"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.enable=true"  
  fp-nginx:
    build:
      context: fp-server
      dockerfile: Dockerfile
    image: registry.gitlab.com/aperez4/fp/fp-nginx:latest
    depends_on:
      - "fp-elb"   
    networks:
      private:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "fp-nginx"
      public:
    ports:    
      - "9802:80"  
    labels:
      - "constraints.zone=fp"
      - "traefik.http.routers.fp-nginx.rule=PathPrefix(`/`)"
      - "traefik.http.services.fp-nginx.loadbalancer.server.port=80"
      - "traefik.backend=fp-nginx"
      - "traefik.port=80"
      #- "traefik.backend.healthcheck.path=/health"
      - "traefik.enable=true"
    # volumes are commented due to manual copy in circle config.xml
    # volumes:
      # - ./fp-server/html:/usr/local/openresty/nginx/html
      # - ./fp-server/templates:/usr/local/openresty/nginx/templates
      # - ./fp-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf 
      # this differs from a normal -v folder mount to maintaine with/out traefik 
      # - ./fp-server/conf/conf.d/default-traefik.conf:/etc/nginx/conf.d/default.conf

networks:
  # everything that is *only* on "internal network" cannot talk to WAN
  private:
    internal: true
  # add this network to a container to make it talk to the rest of the world
  public:
