/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeaSpot
 */
export interface TeaSpot {
    /**
     * 
     * @type {string}
     * @memberof TeaSpot
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeaSpot
     */
    geo?: string;
    /**
     * 
     * @type {string}
     * @memberof TeaSpot
     */
    photo?: string;
    /**
     * Tea types that are available to order
     * @type {Array<string>}
     * @memberof TeaSpot
     */
    teaTypes?: Array<string>;
}

export function TeaSpotFromJSON(json: any): TeaSpot {
    return TeaSpotFromJSONTyped(json, false);
}

export function TeaSpotFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeaSpot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'geo': !exists(json, 'geo') ? undefined : json['geo'],
        'photo': !exists(json, 'photo') ? undefined : json['photo'],
        'teaTypes': !exists(json, 'teaTypes') ? undefined : json['teaTypes'],
    };
}

export function TeaSpotToJSON(value?: TeaSpot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'geo': value.geo,
        'photo': value.photo,
        'teaTypes': value.teaTypes,
    };
}


